server:
  port: 8762
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zxn-rcy/springclouddemo.git
          search-paths: config
          username: 913883783@qq.com
          password: zxn&19980627
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/